# Generated by Django 6.0 on 2026-02-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_created_at_game_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='max_play_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_play_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
