# Generated by Django 6.0 on 2026-04-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='topic',
            field=models.CharField(choices=[('lending', 'Lending'), ('event', 'Event query'), ('general', 'General query'), ('other', 'Other')], max_length=20),
        ),
    ]
