# Generated by Django 6.0 on 2026-04-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_contactmessage_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='topic',
            field=models.CharField(choices=[('lending', 'Lending'), ('event', 'Events'), ('general', 'General'), ('other', 'Other')], max_length=20),
        ),
    ]
